чм

diff --git a/landing/.github/workflows/ci-cd.yml b/landing/.github/workflows/ci-cd.yml
--- a/landing/.github/workflows/ci-cd.yml
+++ b/landing/.github/workflows/ci-cd.yml
@@ -68,6 +68,15 @@ jobs:
           name: coverage
           path: landing/coverage
 
+      - name: Debug build path
+        run: |
+             echo "Current working directory:"
+             pwd
+             echo "Landing directory contents:"
+             ls -la landing
+             echo "Build directory contents:"
+             ls -la landing/build || echo "Build directory not found!"
+             
   deploy:
     runs-on: ubuntu-latest
     needs: test
@@ -79,15 +88,6 @@ jobs:
       - name: Install lftp
         run: sudo apt-get update -qy && sudo apt-get install -y lftp
       
-      - name: Debug build path
-        run: |
-           echo "Current working directory:"
-           pwd
-           echo "Landing directory contents:"
-           ls -la landing
-           echo "Build directory contents:"
-           ls -la landing/build || echo "Build directory not found!"
-
       - name: Deploy via FTP
         env:
           FTP_SERVER: ${{ secrets.FTP_SERVER }}
