111

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -78,12 +78,15 @@ jobs:
       
       - name: Install lftp
         run: sudo apt-get update -qy && sudo apt-get install -y lftp
-      - name: Debug working directory
+      
+      - name: Debug build path
         run: |
-         echo "Current working directory:"
-         pwd
-         echo "Root directory contents:"
-         ls -la
+           echo "Current working directory:"
+           pwd
+           echo "Landing directory contents:"
+           ls -la landing
+           echo "Build directory contents:"
+           ls -la landing/build || echo "Build directory not found!"
 
       - name: Deploy via FTP
         env:
@@ -96,5 +99,5 @@ jobs:
           set ftp:ssl-protect-data true;
           set ssl:verify-certificate no;
           open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER;
-          mirror --verbose --reverse --delete --continue ./landing/build dev.finby.tech
+          mirror --verbose --reverse --delete --continue landing/build dev.finby.tech
           "
